#!/usr/bin/env python
"""Generate SYNTHETIC-ALPHA: a complete simulated corpus for pipeline work.

WHAT THIS IS
------------
A fully-populated corpus with every field the study design calls for, including
the ones the college does not hold: licensure outcome, sex, age band, entry
qualification band, and region. It exists so the full analysis, including the
parts that cannot run on the real extraction, can be exercised and stress-tested
before real outcomes arrive.

WHAT THIS IS NOT
----------------
Evidence. Every outcome in this file was generated by the logistic model in
`outcome_model.generate`, from coefficients chosen by the author. A model
trained here recovers those coefficients, so any result is a property of this
script, not a finding about students. In particular:

  - Hypothesis 2 (academic indicators outrank demographics) CANNOT be tested
    here. The demographic effect is a parameter set in outcome_model.py; a
    test would recover the setting and prove nothing.
  - Discrimination figures cannot be reported. They measure how learnable the
    generated relationship is.
  - The prevalence is an assumption, not a measurement. No published
    first-attempt failure rate for these programmes was available at the time
    of writing.

Legitimate uses: verifying the pipeline end to end, checking that the fairness
and demographic code paths execute, and asking what a larger sample would do to
confidence intervals. Illegitimate use: any number in the Results chapter.

Grounding in real data
----------------------
Academic features are sampled from a Gaussian copula fitted to the 110 real
records, so their joint distribution follows the real cohort rather than a
hand-set one. Demographic marginals are sampled from the 56 consented survey
responses. The outcome relationship is the only wholly invented component, and
it is documented below.

Usage:
    ml_env/bin/python scripts/build_synthetic_alpha.py [--rows N] [--prevalence P]
"""
import argparse
import sys
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

import schema                    # noqa: E402
import synthetic_data            # noqa: E402
import outcome_model           # noqa: E402

SOURCE = REPO_ROOT / "data" / "model_dataset_2021_2022.xlsx"
OUTPUT = REPO_ROOT / "data" / "SYNTHETIC_alpha_corpus.xlsx"

DEFAULT_ROWS = 330          # roughly six cohorts at the observed ~55 per year
SEED = 42

# Prevalence, coefficients, noise and the plausibility band all live in
# outcome_model.py so this corpus and the outcome-return workbooks cannot
# disagree. See that module's docstring for why prevalence is swept.
DEFAULT_PREVALENCE = outcome_model.PRIMARY_PREVALENCE
PLAUSIBLE_AUC = outcome_model.PLAUSIBLE_AUC

# Demographic marginals, taken from the 56 consented survey responses.
GENDER = {"Female": 0.857, "Male": 0.143}
AGE_BAND = {"25-29": 0.446, "20-24": 0.321, "30+": 0.232}
WASSCE_BAND = {"13-18 (Good)": 0.446, "6-12 (Excellent)": 0.333,
               "19-24 (Average)": 0.185, "25-36 (Below Average)": 0.036}
REGION = {"Greater Accra": 0.357, "Volta": 0.232, "Ashanti": 0.107,
          "Eastern": 0.089, "Bono": 0.071, "Ahafo": 0.054, "Other": 0.090}


def _sample_categorical(rng, mapping, n):
    keys = list(mapping)
    probs = np.array([mapping[k] for k in keys], dtype=float)
    return rng.choice(keys, size=n, p=probs / probs.sum())


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rows", type=int, default=DEFAULT_ROWS)
    parser.add_argument("--prevalence", type=float, default=DEFAULT_PREVALENCE)
    args = parser.parse_args()

    if not SOURCE.exists():
        sys.exit(f"Missing {SOURCE}. Run the two consolidation scripts first.")

    real = pd.read_excel(SOURCE, sheet_name="model_data")
    raw_cols = schema.NUMERIC_COLS + schema.CATEGORICAL_COLS
    fit_frame = real[raw_cols + ["cohort_year"]].dropna()
    print(f"Fitting the copula on {len(fit_frame)} real records...")

    # Step 1: academic features, distribution learned from the real cohort.
    corpus = synthetic_data.generate_field_replica(
        fit_frame, "cohort_year", schema.CATEGORICAL_COLS + ["cohort_year"],
        SEED, n_rows=args.rows)
    corpus["cohort_year"] = corpus["cohort_year"].astype(int)

    # Grade counts are resampled independently by the copula, so restore the
    # invariant the proportion features depend on.
    corpus["n_courses"] = corpus[schema.GRADE_COUNT_COLS].sum(axis=1)
    corpus = corpus[corpus.n_courses > 0].reset_index(drop=True)

    rng = np.random.default_rng(SEED)

    # Step 2: demographics, marginals from the real survey.
    corpus["gender"] = _sample_categorical(rng, GENDER, len(corpus))
    corpus["age_band"] = _sample_categorical(rng, AGE_BAND, len(corpus))
    corpus["wassce_band"] = _sample_categorical(rng, WASSCE_BAND, len(corpus))
    corpus["region"] = _sample_categorical(rng, REGION, len(corpus))

    # Step 3: outcome, from the declared logistic model.
    engineered = schema.engineer_features(corpus)
    corpus[schema.TARGET] = outcome_model.generate(
        engineered, args.prevalence, SEED, outcome_model.NOISE_SD_ALPHA)

    corpus.insert(0, "record_type", "SYNTHETIC")
    corpus.insert(1, "student_id",
                  [f"SYN-{i:04d}" for i in range(1, len(corpus) + 1)])

    # Plausibility gate: refuse to ship a corpus that is trivially separable.
    from sklearn.ensemble import GradientBoostingClassifier
    from sklearn.model_selection import cross_val_score
    check = schema.engineer_features(corpus)
    X = pd.get_dummies(check[schema.ALL_FEATURES_V2], drop_first=True)
    auc = cross_val_score(GradientBoostingClassifier(random_state=SEED),
                          X, corpus[schema.TARGET], cv=5,
                          scoring="roc_auc").mean()
    lo, hi = PLAUSIBLE_AUC
    verdict = "within" if lo <= auc <= hi else "OUTSIDE"
    print(f"Learnability check: 5-fold AUC-ROC {auc:.4f} ({verdict} {lo}-{hi})")
    if auc > hi:
        sys.exit(f"Generated relationship is too strong (AUC {auc:.3f}). "
                 "Raise NOISE_SD or lower the coefficients and regenerate.")

    provenance = pd.DataFrame([
        ("record_type", "SYNTHETIC on every row", "Watermark; survives copy-paste"),
        ("academic features", "Gaussian copula fitted to 110 real records", "Real joint distribution"),
        ("gender / age_band / region / wassce_band", "Sampled from 56 consented survey responses", "Real marginals, independent of academics"),
        (schema.TARGET, "Generated by outcome_model.generate()", "ASSUMPTION. Not observed."),
        ("prevalence", f"{args.prevalence}", "ASSUMPTION. No AHPC pass rate is published (pass lists carry no denominator). The 0.261 previously cited here was Amankwaa et al. (2015)'s own 176-student sample, not a population rate; that same paper reports ~50% national nursing failure."),
        ("examining body", "AHPC", "Allied Health Professions Council, Act 857 (2013), pass mark 60%. Not the Nursing and Midwifery Council."),
        ("outcome coefficients", "Academic dominant, demographics weak", "Shaped by Hannaford 2021, Oyler 2025, Amankwaa 2015, Mvula & Msosa 2023"),
        ("rows", f"{len(corpus)}", f"Requested {args.rows}; real cohort is 110"),
        ("learnability", f"AUC-ROC {auc:.4f}", f"Gate: must fall in {lo}-{hi}"),
        ("H2 testable here", "NO", "Demographic effect is a set parameter; a test recovers the setting"),
        ("reportable as findings", "NO", "Outcomes are generated, not observed"),
        ("generated", date.today().isoformat(), "scripts/build_synthetic_alpha.py"),
    ], columns=["field", "how it was produced", "note"])

    with pd.ExcelWriter(OUTPUT, engine="openpyxl") as writer:
        corpus.to_excel(writer, sheet_name="SYNTHETIC_data", index=False)
        provenance.to_excel(writer, sheet_name="PROVENANCE_read_first", index=False)

    print(f"\nWrote {OUTPUT.relative_to(REPO_ROOT)}")
    print(f"  rows {len(corpus)} | prevalence {corpus[schema.TARGET].mean():.3f} "
          f"| predictors {len(schema.ALL_FEATURES_V2)} plus 4 demographics")
    print("  every row carries record_type = SYNTHETIC")


if __name__ == "__main__":
    main()
